### PR TITLE
Revamp design

### PR DESCRIPTION
**Pull request by ishan-me**
## Design Improvements

UI

## Tasks:
1. Added more better UI interface

## Usage Changes:
- Improved and refactoring of tailwind configuration
- Added latest tailwind version
- Added Purge to remove unused css generated by tailwind in prod build

## Remaining Tasks:
- May need some better UI after search

## Risks:
- I don't see risk, mostly just worked in CSS parts

Resolves #54

### CODE REVIEW

**Comment by bipulthapa** [comment]
Screenshot from 2021-01-14 17-55-28

**Comment by bipulthapa** [comment]
@ishan-me The text doesn't look clearly visible in TotalPrs count.
Screenshot from 2021-01-14 17-55-28

**Comment by bipulthapa** [comment]
@ishan-me I think we would also need to further discuss with Sagun Karanjit Dai regarding this revamp design.

**Comment by ishan-me** [comment]
@bipulthapa Will work on this sooner. Thank you.

**Comment by bhattaraib58** [comment]
@ishan-me dai, do we have any updates on this?

**Comment by ishan-me** [comment]
@bhattaraib58 Actually I have not able to work on this. Hopefully I will fix it before Oct. And send a PR.

Thank you for reminder.

**Comment by ishan-me** [comment]
@bipulthapa @bhattaraib58 

Changed overall design and switched to 2021 with new Logo.

Screenshot Attached.

Frogtoberfest-Checker

**Comment by bhattaraib58** [comment]
@ishan-me can you pull in changes from master and fix the merge conflicted files.

**Comment by bhattaraib58** [comment]
@ishan-me  Hmm, there still seems to be merge conflict,

Please perform these steps: 
# Add the remote, call it "upstream":
git remote add upstream git@github.com:leapfrogtechnology/frogtoberfest.git

# Fetch all the branches of that remote into remote-tracking branches
git fetch upstream

# Pull changes from the upstream (leapfrog frogtoberfest master branch)
git pull upstream master

#  ==> Fix conflicts

# After that push your changes 
git push origin [branch]

# ==> Update the screenshot in the PR after conflict fix changes.

**Pull request closed without merging**
