### PR TITLE
Version tailwind upgraded

### PR DESCRIPTION
**Pull request by ishan-me**
## Usage Changes

- Upgraded to latest version of tailwind and improved tailwind configuration
- Implemented tailwind compression, which will remove the unnecessary tailwind css in production build

### CODE REVIEW

**Comment by kabirbaidhya** [comment]
@ishan-me Thanks. Please add a preview screenshot in the PR description.

**Comment by ishan-me** [comment]
@kabirbaidhya For now just upgraded the version. I still need to work on this will shortly wrap it up soon hopefully.

**Comment by bipulthapa** [comment]
@ishan-me Dai if this is still in progress then let's add a `WIP` label or convert this PR to draft for now.

**Comment by ishan-me** [comment]
@bipulthapa I have added another PR which closes this issue.

**Comment by bhattaraib58** [comment]
Closed as included in #54

**Pull request closed without merging**
